### PR TITLE
Fix all (?) cases of autoescaping

### PR DESCRIPTION
**Pull request by Keats**

### CODE REVIEW

**Comment by azemlya** [comment]
Template:

```
{% set s1 = '<"string1">' -%}
{% set s2 = '<"string2">' -%}
<< 1 >> {{ s1 }}{{ s2 }}
<< 2 >> {{ s1 ~ s2 }}
<< 3 >> {{ '<"string1">' ~ '<"string2">' }}
<< 4 >> {{ {'<"key1">': s1, '<"key2">': s2, } }}
<< 5 >> {{ [s1, s2, ] }}
<< 6 >> {{ {'<"key1">': '<"string1">', '<"key2">': '<"string2">', } }}
<< 7 >> {{ ['<"string1">', '<"string2">', ] }}
```

Output:

```
<< 1 >> <"string1"><"string2">
<< 2 >> <"string1"><"string2">
<< 3 >> <"string1"><"string2">
<< 4 >> {<"key1">: '<"string1">', <"key2">: '<"string2">'}
<< 5 >> ['<"string1">', '<"string2">']
<< 6 >> {<"key1">: '&lt;&quot;string1&quot;&gt;', <"key2">: '&lt;&quot;string2&quot;&gt;'}
<< 7 >> ['&lt;&quot;string1&quot;&gt;', '&lt;&quot;string2&quot;&gt;']
```

**Comment by Keats** [comment]
Should be ok now, but it's a bit of a sledgehammer approach which doesn't seem to affect benchmarks though

**Comment by azemlya** [comment]
Thank you so much for your promptness! Yes! Everything is working as it should now. The only problem is escaping single quotes, line breaks, and slashes when outputting structures directly. But, it's necessary for debag, so it's tolerable.

```
{% set s = "\n<div> \\ ' " ~ '"' ~ " & </div>" -%}
<< 1 >> {{ s }}
<< 2 >> {{ s ~ s }}
<< 3 >> {{ "\n<div> \\ ' " ~ '"' ~ " & </div>" ~ "\n<div> \\ ' " ~ '"' ~ " & </div>" }}
<< 4 >> {{ {'<"key1">': s, '<"key2">': s, } }}
<< 5 >> {{ [s, s, ] }}
<< 6 >> {{ {'<"key1">': "\n<div> \\ ' " ~ '"' ~ " & </div>", '<"key2">': "\n<div> \\ ' " ~ '"' ~ " & </div>", } }}
<< 7 >> {{ ["\n<div> \\ ' " ~ '"' ~ " & </div>", "\n<div> \\ ' " ~ '"' ~ " & </div>", ] }}
```

```
<< 1 >>
<div> \ ' " & </div>
<< 2 >>
<div> \ ' " & </div>
<div> \ ' " & </div>
<< 3 >>
<div> \ ' " & </div>
<div> \ ' " & </div>
<< 4 >> {<"key1">: '
<div> \ ' " & </div>', <"key2">: '
<div> \ ' " & </div>'}
<< 5 >> ['
<div> \ ' " & </div>', '
<div> \ ' " & </div>']
<< 6 >> {<"key1">: '
<div> \ ' " & </div>', <"key2">: '
<div> \ ' " & </div>'}
<< 7 >> ['
<div> \ ' " & </div>', '
<div> \ ' " & </div>']
```

**Comment by Keats** [comment]
So in Jinja2:

```
<< 5 >> {{ "\n<div> \\ ' " ~ '"' ~ " & </div>" }}
<< 6 >> {{ {'<"key1">': "\n<div> \\ ' " ~ '"' ~ " & </div>", '<"key2">': "\n<div> \\ ' " ~ '"' ~ " & </div>", } }}
<< 7 >> {{ ["\n<div> \\ ' " ~ '"' ~ " & </div>", "\n<div> \\ ' " ~ '"' ~ " & </div>", ] }}
```

gives

```
<< 5 >> 
<div> \ ' " & </div>
<< 6 >> {"<\"key1\">": "\n<div> \\ ' \" & </div>", "<\"key2\">": "\n<div> \\ ' \" & </div>"}
<< 7 >> ["\n<div> \\ ' \" & </div>", "\n<div> \\ ' \" & </div>"]
```

I'm ... not sure which is the best. It makes sense for debug to print the raw string but the current way also makes sense?

**Comment by azemlya** [comment]
The string should be output as a string. Jinja2 does it right. And, structures like mapping and array are better to be converted to JSON format. In general, Jinja2 does just that. It seems right to me. Characters will be correctly escaped during serialization. And JSON serialization is fast. This is just my opinion, I do not pretend to be correct.

**Comment by Keats** [comment]
Ok I believe it now behaves like Jinja2. I had to rewrite most of the escaping but it's cleaner now

**Pull request merged**
