### PR TITLE
Fix ahash feature

### PR DESCRIPTION
**Pull request by Keats**

### CODE REVIEW

**Comment by azemlya** [comment]
I'm thinking in `tera/Cargo.toml` instead:
```
ahash = ["hashbrown", "hashbrown/serde"]
```
Put it like this:
```
ahash = ["dep:hashbrown", "hashbrown?/serde"]
```
I think it's more correct. Although, it works like that.

**Comment by Keats** [comment]
I need to test the difference between hashbrown and just using ahash

**Comment by azemlya** [comment]
I tried to compile my program in various ways. Only I can't disable `glob_fs`, because I have templates loaded from the file system. Everything compiles and works as it should in all variants. The rendering time is of course different. With ahash, it's a little faster. I didn't find any errors. But, of course, it is better to double-check. Run your tests too.

**Comment by Keats** [comment]
I've switched to using ahash directly so it's more explicit than hashbrown and i didn't get significant differences in benches

**Comment by azemlya** [comment]
Cool! I switched to the last commit in the master without any problems. Everything works as it should. The tests are successful. Thank you, Vincent!

**Pull request merged**
