### PR TITLE
fix: Change ForLoop.context to HashMap

### PR DESCRIPTION
**Pull request by jalil-salame**
Improvements of 6% in big-table and mostly 1-2% in others

### CODE REVIEW

**Comment by jalil-salame** [comment]
BTreeMap's drop was really noticable in the flamegraph of big-table, now it is gone. Consider changing other structures to HashMaps or Vecs

**Comment by jalil-salame** [comment]
This is about as much work as I can sneak in rn, I still have some ideas, but not enough time.

As of commit `2f2e6b0` this is the change compared to `master`:

Summary:

| Bench             | Change       |
|-------------------|--------------|
| escape_html_short | within noise |
| escape_html_long  | within noise |
| simple            | within noise |
| slightly complex  | within noise |
| big-context       | -3.1%        |
| big-table         | -13%         |
| teams             | +9.2%        |
| serialization     | -9.8%        |

Regression in `teams`, otherwise good or neutral.

Full criterion output:

```
     Running benches/escape.rs (target/release/deps/escape-c0461a370af31289)
Gnuplot not found, using plotters backend
escape_html_short       time:   [463.72 ns 468.39 ns 473.04 ns]
                        change: [-1.6866% -1.0429% -0.4135%] (p = 0.00 < 0.05)
                        Change within noise threshold.
Found 22 outliers among 100 measurements (22.00%)
  19 (19.00%) low severe
  1 (1.00%) low mild
  1 (1.00%) high mild
  1 (1.00%) high severe

escape_html_long        time:   [8.5109 µs 8.5413 µs 8.5909 µs]
                        change: [-0.8372% -0.5737% -0.3040%] (p = 0.00 < 0.05)
                        Change within noise threshold.
Found 2 outliers among 100 measurements (2.00%)
  2 (2.00%) high severe

     Running benches/parsing.rs (target/release/deps/parsing-b16a59c08ca3a6b4)
Gnuplot not found, using plotters backend
simple                  time:   [4.3914 µs 4.3947 µs 4.3995 µs]
                        change: [+0.5660% +0.6501% +0.7370%] (p = 0.00 < 0.05)
                        Change within noise threshold.
Found 5 outliers among 100 measurements (5.00%)
  3 (3.00%) high mild
  2 (2.00%) high severe

slightly complex        time:   [5.4771 µs 5.4791 µs 5.4813 µs]
                        change: [-1.7065% -1.1500% -0.8473%] (p = 0.00 < 0.05)
                        Change within noise threshold.
Found 1 outliers among 100 measurements (1.00%)
  1 (1.00%) high mild

     Running benches/templates.rs (target/release/deps/templates-4d9f1bbf18a22e08)
Gnuplot not found, using plotters backend
big-context             time:   [4.0847 µs 4.0908 µs 4.0975 µs]
                        change: [-3.2542% -3.0796% -2.8945%] (p = 0.00 < 0.05)
                        Performance has improved.

Benchmarking big-table: Warming up for 3.0000 s
Warning: Unable to complete 100 samples in 5.0s. You may wish to increase target time to 8.2s, enable flat sampling, or reduce sample count to 50.
big-table               time:   [1.5668 ms 1.5704 ms 1.5740 ms]
                        change: [-13.343% -12.984% -12.626%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 1 outliers among 100 measurements (1.00%)
  1 (1.00%) low mild

teams                   time:   [4.8392 µs 4.8483 µs 4.8567 µs]
                        change: [+8.8702% +9.1804% +9.5103%] (p = 0.00 < 0.05)
                        Performance has regressed.
Found 4 outliers among 100 measurements (4.00%)
  3 (3.00%) low mild
  1 (1.00%) high mild

     Running benches/value.rs (target/release/deps/value-e6cff510a72a1809)
Gnuplot not found, using plotters backend
serialization           time:   [784.02 ns 785.82 ns 787.41 ns]
                        change: [-10.180% -9.7568% -9.2697%] (p = 0.00 < 0.05)
                        Performance has improved.
```

**Comment by jalil-salame** [comment]
`big-table` ends up being only 4% slower on tera2, than in tera1.
`teams` is still 20% slower

**Comment by jalil-salame** [comment]
You can problably turn `ForLoop` into an iterator, thus reducing the number of `unwrap`/`except`s being called.

**Comment by Keats** [comment]
Looking good thanks! I don't really get a difference on the teams benchmark on my machine

**Pull request merged**
