### PR TITLE
feat(benches): Add iai benchmarks

### PR DESCRIPTION
**Pull request by jalil-salame**
iai uses valgrind to get perf counters from the cpu making jitter less of an issue. You need to have valgrind installed to run the benchmarks though.

This fixes the jitter in the `escape_html` benchmarks for me, and should give better numbers to perf imporvements (seeing that the current benchmarks are in the mili-micro second range reductions in the instruction count/cache hits is more noticeable.

### CODE REVIEW

**Comment by Keats** [comment]
iai doesn't seem maintained? Maybe https://github.com/osiewicz/calliper would work, same concept

**Comment by jalil-salame** [comment]
> iai doesn't seem maintained? Maybe https://github.com/osiewicz/calliper would work, same concept

This uses a fork of iai that AFAIK is maintained (last new version came 24min ago).

https://github.com/Joining7943/iai-callgrind

**Comment by Keats** [comment]
Let's use that

**Comment by jalil-salame** [comment]
> Let's use that

The fork? That is what this PR uses, if you want me to switch it to caliper, I can do that too.

**Comment by Keats** [comment]
Fork or caliper, whichever you think is nicer

**Comment by jalil-salame** [comment]
> Fork or caliper, whichever you think is nicer

I'll check caliper out but this is already using the fork.

**Comment by jalil-salame** [comment]
UI/UX of caliper is much worse than `iai-callgrind`. I'd stick with `iai-callgrind`.

**Comment by Keats** [comment]
Can you resolve the conflicts? I'll merge it after

**Comment by jalil-salame** [comment]
> Can you resolve the conflicts? I'll merge it after

There!

**Comment by Keats** [comment]
This is actually annoying because valgrind doesn't work on mac so i can't run the benches by default anymore :/ 
I'll comment them out in Cargo.toml for now

**Pull request merged**
